# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build and deploy

on:
  push:
    branches: [ master ]
  schedule:
    - cron: '31 12 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v2
      with:
        node-version: 14.x
        cache: 'npm'
    - run: npm i
    - run: node fetchData.js
    - run: npm run build --if-present
    - name: GitHub Pages action
      # You may pin to the exact commit or the version.
      # uses: peaceiris/actions-gh-pages@bbdfb200618d235585ad98e965f4aafc39b4c501
      uses: peaceiris/actions-gh-pages@v3.7.3
      with:
        # Set custom domain
        cname: ru.index.community
